export const PIZZAS_IS_FETCHING = 'PIZZAS_IS_FETCHING'
export const PIZZAS_IS_SUCCESS = 'PIZZAS_IS_SUCCESS'
export const PIZZAS_IS_FAILURE = 'PIZZAS_IS_FAILURE'

export const PIZZA_DETAIL_IS_FETCHING = 'PIZZA_DETAIL_IS_FETCHING'
export const PIZZA_DETAIL_IS_SUCCESS = 'PIZZA_DETAIL_IS_SUCCESS'
export const PIZZA_DETAIL_IS_FAILURE = 'PIZZA_DETAIL_IS_FAILURE'

export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_FROM_CART = 'DELETE_FROM_CART'

export const CHANGE_QTY = 'CHANGE_QTY'
